### PR TITLE
Migrate to 3.0.2 swift syntax;

### PR DESCRIPTION
**Pull request by Antondomashnev**
Hi, thanks for the wrapper 👍 

This PR addresses the issue #5 and fixes all errors and warnings.

### CODE REVIEW

**Comment by gurinderhans** [comment]
I am going to trust you on the correctness of the upgrade to 3.0.2, but just had one request, can we not change the `.gitignore` by adding the `.DS_Store`, I always assume people have it ignored locally. Just a personal thing :)

Remove the `.gitignore` changes, and I will merge 👍

**Review by gurinderhans — CHANGES_REQUESTED** [review]
Let's not change the .gitignore at all.

**Comment by gurinderhans** [comment]
Another thing, you might want to merge into this branch https://github.com/gurinderhans/SwiftFSWatcher/tree/swift-3.0, since master is swift 2.0, after the merge I can put all this into master

**Comment by Antondomashnev** [comment]
@gurinderhans sorry about gitignore, I keep forgetting to put the `DS_Store` into the global excluded files 😄 .

> Another thing, you might want to merge into this branch https://github.com/gurinderhans/SwiftFSWatcher/tree/swift-3.0

Perfect, it's merged now and I'll open another PR targeting to swift-3.0.

**Pull request closed without merging**
